# Global application settings
[global]
# Set the default frame rate (updates per second)
frame_rate =  60.0
# Enable debug logging globally
debug_mode = true

[bobble_sort]
time_scale = 1.0

[langtons_ant]
time_scale = 1.0

[maze_generation]
time_scale = 1.0

[boids]
time_scale = 1.0
num_boids = 80
min_distance = 2.0
max_range = 10.0
neighbor_dist = 5.0
max_velocity = 0.1
cohesion_weight = 0.002
alignment_weight = 0.0005
